### ISSUE TITLE
Change default user to www-data in Apache2 Images

### ISSUE THREAD

**Issue by martialblog** [martialblog/docker-limesurvey#60]
I want to change the default user to www-data in Apache2 Images. However, that means the port 80 won't work anymore and a the new default port would be 8080, but also customizable thanks to https://github.com/martialblog/docker-limesurvey/pull/59

**Comment by martialblog** [comment]
@jacksgt I don't see how I can make this change transparent to the current users... any ideas?

**Comment by eidottermihi** [comment]
It would definitely be a breaking change for the vast majority of users of `latest`,`4`,`4-apache` because I would assume most people didn't customize to run on non-privileged ports.

As an alternative, provide new image tag like `4-apache-non-root` (I'm bad at naming 😄 ) based on a new Dockerfile. But that would require maintaining another "flavour" of the image which increases maintaining costs.

**Comment by martialblog** [comment]
Jup that's what I figured too. Then again, I think the benefits would outweigh the troubles of changing the port. Even if it "breaks" something at first :thinking:

**Comment by jacksgt** [comment]
I am generally in favor of using `www-data` instead of `root` (and changing to port > 1024), but against breaking the backwards compatibility.
The grafana image had a similar issue and they did the "migration" on a major version bump of Grafana:
https://grafana.com/docs/grafana/latest/installation/docker/#migrate-from-previous-docker-containers-versions

I have no clue when or if there is going to be a 5.x release of Limesurvey, but until the `*-non-root` option seems sensible.

**Comment by martialblog** [comment]
There's an upcoming update from 4.5.2 (build 210426) to 4.6.0 (build 210504), could be used for the major change.

**Comment by jacksgt** [comment]
Ah ok, now I got the point of #61 
Personally, I wouldn't do this breaking change in a minor release (4.5->4.6), though.

**Comment by martialblog** [comment]
I don't know when a major release will be... could be a while. Thought this might be a good chance to fix, what I should have done right in the first place. Maybe breaking things for security's sake isn't too bad? :shrug: 

I'm gonna test the change and provide details for the users in the README on how to migrate.

**Comment by jacksgt** [comment]
I understand where you are coming from. From the developers point of view it seems like a small change (with large benefits), but that might not be the same for the users of the image (we don't even know how many there are, but there are 1M+ pulls of the image, so probably quite a few).
Would you really appreciate it if one of the dozen images you are running in production has a breaking change in a minor version?

**Comment by martialblog** [comment]
Guess you're right. Maybe let's ease into it. I'll provide `-rootless` tags for now

Gotta check if there are build-args in the DockerHub autobuilds, I don't wanna add new Dockerfiles

**Comment by martialblog** [comment]
I just pushed rootless versions of the Apache Images to docker.io - Feel free to test that stuff, I assume the permissions on existing volumes needs to be adjusted.

**Comment by martialblog** [comment]
There it is. LS 5.0 https://github.com/LimeSurvey/LimeSurvey/releases/tag/5.0.0%2B210526

**Comment by jacksgt** [comment]
Wow, convenient timing!
